---
- hosts: all
  gather_facts: no
  serial: 1
  tasks:


  - name: get package info
    package_facts:

  - name: print out the required info
    debug:
      msg: |
        Packages => {{ ansible_facts.packages | list }}
##        Packgage name: {{ ansible_facts.packages | map(attribute='name') | list }}
#        Packgage version: {{ ansible_facts.packages.http[0].version | default() }}
