---
- hosts: all
  become: 1
  tasks:


  - name: write host file on master node
    template:
      src: hosts.j2
      dest: /etc/hosts
      mode: 0644
      owner: root
      group: root
      setype: net_conf_t
    delegate_to: rh1
